# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 9090
  connection-timeout: 5000ms
  servlet:
    context-path: /
#spring:
#    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/renren_fast
#        username: root
#        password: 123456

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: io.renren.modules.*.entity

  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
spring:
  profiles:
#    active: test
    active: dev

  mail:
    host: smtp.139.com
    username: 18236974899@139.com
    password: zl@123@456
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#    port: 465
  thymeleaf:
    prefix: classpath:/static/

OSS:
  ENDPOINT: 127.0.0.1
  UID: 123
  ACCESS-KEY: 123
  SECRET-KEY: 123
  bucketName: 123
file:
  storage:
    type: sftp
    port: 30787
    username: zhouliang
    password: 12345678
    url: 172.16.100.10
